# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: teectl
    displayName: installed teectl and deploy service using teectl
    jobs:
    -  job: downloadAndTeectlVersionCheck
       displayName: 
       steps:

       - task: CmdLine@2
         inputs:
            script: |
              echo "Download the teectl for windows"
              curl -o teectl.zip https://s3.amazonaws.com/traefikee/binaries/v2.0.5/teectl/teectl_v2.0.5_windows_amd64.zip
              tar xzvf teectl.zip
              echo "dir command result"
              dir
              echo "teectl Version Result"
              teectl version
            
              echo "Connect to kubernetes"
              az login --use-device-code
              az account set --subscription 9f5e2100-3a33-4deb-aa07-ec5f521aebc3
              az aks get-credentials --resource-group Demok8 --name traefikcluster
              kubectl get deployments --all-namespaces=true
              echo "teectl setup command Result"
              teectl setup --kubernetes
              
