# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: teectl
    displayName: installed teectl and deploy service using teectl
    jobs:
    -  job: copyteectlfromgithub
       displayName: 
       steps:

       - task: CmdLine@2
         inputs:
            script: |
              echo Write your commands here
              
              echo "teectl Result"
              dir
              #"/home/vsts/work/1/s/teectl.exe version"
              teectl version
              #teectl.exe
